defaults:
  - _self_
  - trainer: defaults
  - optimizer: adam
  - experiment: era5_uncond
  - system: nersc

seed: 1234
resume: ""
dry_run: false

hydra:
  run:
    dir: results/${experiment_name}/${now:%Y%m%d_%H%M%S}
  job:
    chdir: true